### ISSUE TITLE
Does this work on the standard Pi Zero W?

### ISSUE THREAD

**Issue by RealAquilus** [jaromaz/MacintoshPi#2]
The readme tells that this doesn't work on the Raspberry Pi 4 but no information are given about Raspberry Pi Zero W

**Comment by jaromaz** [comment]
I don't own a Raspberry Pi Zero W and just haven't tested it.
Let us know if it works.

**Comment by aptonline** [comment]
I can confirm it works great on a Pi Zero W2 although Mac OS 9 is a tad sluggish so will be even slower on the Zero W.

**Comment by mwy912** [comment]
I am trying on a Pi Zero W and the screen scrolls horizontally.... Rather than being a static picture, it moves across the screen from left to right.  I'm not sure if that's an issue with the pi zero not supporting, or I need to do something with my setup.

https://user-images.githubusercontent.com/66441897/191960448-bc728ab1-bb49-4231-a425-fd04b04b37cd.mov
