### ISSUE TITLE
SDL2 not being built?

### ISSUE THREAD

**Issue by rainbowmst3000** [jaromaz/MacintoshPi#30]
I am using a Zero 2 W with Buster 32bit full version in CLI mode and following the instructions exactly. However, the compliation of SDL2 appears not to be triggered and there is no indication that it is happening resulting in Basilisk not being compiled. Any insights?

![PXL_20231019_185744562 PORTRAIT ORIGINAL](https://github.com/jaromaz/MacintoshPi/assets/74487607/ef8b4d29-7585-40dc-a543-5bef92834cd7)

**Comment by RobRS7** [comment]
I too am receiving SDL2 errors when trying to install MacintoshPi on a Pi Zero 2 W running under 32bit Pi OS (Legacy)
I get an SDL2 error during the installation of Basilisk II -

![2023-09-28 13 30 09](https://github.com/jaromaz/MacintoshPi/assets/149151707/acef400c-4db0-4e6a-9c51-538251043edb)

Another SDL2 error during the installation of SheepShaver -

![2023-09-28 13 30 15](https://github.com/jaromaz/MacintoshPi/assets/149151707/f704af01-d279-483c-a07e-84a02e44001d)

HTH?

**Comment by brnrds-git** [comment]
+1, on a Raspberry Pi 3 running a "full" legacy install and following all instructions.

**Comment by jaromaz** [comment]
buster is no longer Legacy, it is now the newer bullseye distribution. 
https://www.cnx-software.com/2023/10/12/raspberry-pi-os-upgraded-to-debian-12-bookworm/

For now, I suggest you try the build on the image available below (haven't tried it yet):
https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-04-07/

Since all this software is legacy, I will try to build MacintoshPi images soon and make them available for download here.

**Comment by rainbowmst3000** [comment]
Thanks, but this doesn't work either. Same issue. Also, I tried both Buster and Bullseye. Neither work.

**Comment by jaromaz** [comment]
I'm going to check it out next week.

**Comment by jaromaz** [comment]
All fixed - read the new [Installation section](https://github.com/jaromaz/MacintoshPi#installation).

**Comment by rainbowmst3000** [comment]
Thanks so much!
