### ISSUE TITLE
What prevents Pi 4(00) compatibility?

### ISSUE THREAD

**Issue by webspacecreations** [jaromaz/MacintoshPi#4]
Historically, I know the GPU drivers were problematic on Pi 4(00), but that's been resolved for some time now. I know Baslisk II & SheepShaver will compile on that hardware, although I haven't yet tested with the latest 64-bit builds. If I were going to contribute to getting this working on Pi 4(00), where should I focus that effort?

Do you have any interest in including Apple II / IIGS emulators to "close the loop" on this line of retro emulation (assuming they could be launched from command line like the mac ones)?

**Comment by jaromaz** [comment]
I would love to see an Apple II, Apple I and Altair 8800 emulators (but with a full panel - Altair32 style). Then we would cover the history of most significant personal computers up to the year 2000.

BMC64 works only on Raspberry Pi Zero, 2 and 3 that's why I focused on those versions. If you manage to create a version for Raspberry Pi 4, go ahead and create a pull request.
